<template>
<!-- We would like you to render 12 NFTs in the desktop full width view, but limit it to 3 NFTs if mobile width (examples in the design)-->
<!-- Here you will see conditional rendering separating between mobile Nfts and normal. You may use your own logic for displaying the nfts between the mobile view and desktop-->
    <div>
        <div v-if="mobileNFTs && mobileNFTs.length > 0">
            <div v-for="(item, index) in mobileNFTs" :key="index"> <!--This will loop through all the items in mobileNFTs Array-->
            <!--Display and style as appropriate-->
            </div>
        </div>
        <div v-else>
            <!--You may display the normal NFTs as such -->
            <div v-for="(item, index) in NFTs" :key="index"> <!--This will loop through all the items in NFTs Array generated by the computed method and display what you want-->
                <!--Display and style as appropriate-->
            </div>
        </div>
    </div>
</template>

<script>
export default {
  name: 'Home-NFT-Display',
  data() {
    return{
      mobileNFTs: [] // You may use this to display limited NFTs
    }
  },
  mounted () {
  },
  created () {
    window.addEventListener('resize', this.checkScreen) // On window resize: runs the checkScreen method
  },
  methods: {
    checkScreen () {
      // You will have to add to this method if you want the expected results. Or abandon it entirely and make your own
      this.windowWidth = window.innerWidth
      if (this.windowWidth <= 600) {
          // do something
      } else if (this.windowWidth > 600) {
          // do something
      }
    },
  },
  computed: {
    GenerateNFTData() {
      const NFTs = []
      // Generate NFT data and push into the NFT array
      // You can create a loop that loops through n NFTS generating the data with unique IDs
      // Use these generated NFTs to display on the market.
      /** NFT data should look something like:
       * name: 'NFT-1' where 1 is the value of i in your loop
       * artist: 'Unknown Artist'
       * price: 100 #you may keep this random
       * image: this should be any image of your choosing or selected from the shared XD file
       */
      return NFTs
    }
}
}
</script>

<style scoped>

</style>